server:
  port: 80
  servlet:
    context-path: /jeewx
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
 
spring:
    # 设置静态文件路径，js,css等
    mvc:
         pathmatch:
            use-suffix-pattern: false
            use-registered-suffix-pattern: true
         contentnegotiation:
            favor-path-extension: false
         static-path-pattern: /**
    resource:
         static-locations: classpath:/static/,classpath:/public/
    datasource:
        name: mysql
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://127.0.0.1:3306/jeewx-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false
          username: root
          password: root
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
 
mybatis:
  mapper-locations: classpath*:com/jeecg/p3/**/sqlmap/*.xml
  type-aliases-package: com.jeecg.p3.*.entity
 
jeewx:
    #拦截器配置
    interceptor:
       #是否开启
       is-open: true
       #排除拦截URL
       excludeUrls:
         login-interceptor: /system/back/article/toIndex.do,/system/back/article/toArticle.do,/system/preSelectJwid.do,/system/back/home.do,/system/back/jwSystemAccountAPI/getUserAccountAmount.do,/back/backIndex/home.do
         access-sign-interceptor: /api/cms/**,/cms/**,/wechatController.do,/weixinNewsController/goContent.do,/weixinLinksucai/link.do,/linksucai/link.do,/fx/mall/payCallBack.do,/newsController/getNewsClassify.do,/newsController/getNewslist.do,/CommonController/sendMsgCode.do
    #Redis缓存配置
    redis:
       ip: 127.0.0.1
       port: 6379
       password:
       pool:
          maxTotal: 1024
          maxIdle: 200
          maxWaitMilli: 1000
          testOnBorrow: true
          testOnReturn: true
    #邮箱配置
    mail:
      smtpHost: smtp.exmail.qq.com
      sender: jeewx@jeecg.org
      user: jeewx@jeecg.org
      pwd:
    #阿里云短信接口秘钥
    sms:
      accessKeyId: 
      accessKeySecret:
    path :
        #文件上传根目录
        upload: D://upImgs

